{******************************************************************************}
{                                                                              }
{   Library:          Fundamentals 4.00                                        }
{   File name:        cCipher.inc                                              }
{   Description:      Cipher library defines                                   }
{                                                                              }
{******************************************************************************}

{.DEFINE DEBUG}
{.DEFINE SELFTEST}

{$INCLUDE cDefines.inc}

